services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb_data:/data/db
  user-service:
    image: user-service
    build: .
    container_name: user-service
    restart: always
    ports:
      - '${DOCKER_SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

volumes:
  mongodb_data:
