version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ['npm', 'run', 'start:dev']

volumes:
  mongodb_data:
